### ISSUE TITLE
Typo on server-config.sh

### ISSUE THREAD

**Issue by bfreezy** [logicnow/BlueSky#1]
Line 188 currently has:

`cp /usr/local/bin/sendmail-whois-lines.conf /etc/fail2ban/action.d/sendEmail-whois-lines.conf`

The "sendmail-whois-lines.conf" should be "sendEmail-whois-lines.conf"

If you don't change that value, you will get this error in the script output:

`cp: cannot stat '/usr/local/bin/sendmail-whois-lines.conf': No such file or directory`

**Comment by bestmacs** [comment]
D'oh.  Thanks
