### ISSUE TITLE
Display dates in local or specified time zone.

### ISSUE THREAD

**Issue by sphen13** [logicnow/BlueSky#11]
Im not familiar with appgini - although i suppose i could take a look... was wondering if we could set a timezone to use for the display of dates within the dashboard.  currently last check in date etc is in UTC.

**Comment by bestmacs** [comment]
Run this in Ubuntu to set your time zone.  The check-in times will update when the records are updated. (i.e. on next check-in it will change from UTC to your local TZ)

dpkg-reconfigure tzdata

**Comment by bestmacs** [comment]
Updated the troubleshooting page in the wiki.  (I also forgot to tell you to reboot after running the command.) https://github.com/logicnow/BlueSky/wiki/Troubleshooting

**Comment by sphen13** [comment]
duh - thanks :)
