### ISSUE TITLE
function isEmail($email) fails to recognize new TLDs.

### ISSUE THREAD

**Issue by grigutis** [logicnow/BlueSky#12]
For example, .technology TLDs are not accepted. I see that there is an [email validation filter in php](http://php.net/manual/en/filter.examples.validation.php) that would work for this case:

`filter_var($email, FILTER_VALIDATE_EMAIL)`

but it won't recognize the default case of root@localhost.

**Comment by sphen13** [comment]
pushed to 2.3 branch
