### ISSUE TITLE
Wiki modification

### ISSUE THREAD

**Issue by sphen13** [logicnow/BlueSky#4]
Not sure how to do PR's to wiki pages :)  the getting started page has 2 typos:

https://github.com/logicnow/BlueSky/wiki/Getting-Started

The 2 paths that reference the /usr/local/Bluesky/Server directory do not have "Server" with the initial cap.

- run BlueSky server-config `sudo /usr/local/bin/BlueSky/server/server-config.sh`
- run BlueSky server-config `sudo /usr/local/bin/BlueSky/Server/server-config.sh`

Also, you may want to configure `/usr/local/bin/BlueSky/server/emailHelper.sh` with your preferred SMTP setup so that the server can email you [notifications, alerts](https://github.com/logicnow/BlueSky/wiki/Notifications-and-Alerts), and Fail2ban alerts.
Also, you may want to configure `/usr/local/bin/BlueSky/Server/emailHelper.sh` with your preferred SMTP setup so that the server can email you [notifications, alerts](https://github.com/logicnow/BlueSky/wiki/Notifications-and-Alerts), and Fail2ban alerts.

**Comment by bestmacs** [comment]
Fixed.  :-)
